# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8988dd8e9cf6e0015e8e5c51f8a6899df67a7058763739ed0d5db8766aca5adeb6ccbc46ac58025d32bc1b01d644b5808e25d8d70b4737c7952ec2b3f8aa3313

test:
  secret_key_base: fb9df1642c4b67fe52c5b23d4e2d97c3e08c517422b4297df2f7944c17f7129ec68111c9599d471143d0ae3d702e605d1b35c5cf4f8fe40624ca4bf042c19a38

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
